# Generated by Django 4.1.3 on 2022-11-20 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConferenceReservation',
            fields=[
                ('id_conference', models.IntegerField(primary_key=True, serialize=False)),
                ('reservation_date', models.DateField()),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('number_of_people', models.IntegerField()),
                ('id_client', models.IntegerField()),
                ('id_worker', models.IntegerField()),
            ],
            options={
                'db_table': 'conference_reservation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StayReservation',
            fields=[
                ('id_stay', models.IntegerField(primary_key=True, serialize=False)),
                ('reservation_date', models.DateField()),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('number_of_people', models.IntegerField()),
                ('check_in', models.DateField(blank=True, null=True)),
                ('check_out', models.DateField(blank=True, null=True)),
                ('id_client', models.IntegerField()),
                ('id_worker', models.IntegerField()),
            ],
            options={
                'db_table': 'stay_reservation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ConferenceRoomReservation',
            fields=[
                ('id_conference', models.OneToOneField(db_column='id_conference', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='reservations.conferencereservation')),
                ('id_conference_room', models.IntegerField()),
            ],
            options={
                'db_table': 'conference_room_reservation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StayRoomReservation',
            fields=[
                ('id_stay', models.OneToOneField(db_column='id_stay', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='reservations.stayreservation')),
                ('id_room', models.IntegerField()),
            ],
            options={
                'db_table': 'stay_room_reservation',
                'managed': False,
            },
        ),
    ]
